# Generated by Django 5.1.2 on 2024-11-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_food_desciption_food_promotion_end_at_and_more'),
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foods.food'),
        ),
    ]
