# Generated by Django 5.1.2 on 2024-11-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_food_desciption_food_promotion_end_at_and_more'),
        ('app_general', '0002_subscription_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='food',
        ),
        migrations.AddField(
            model_name='subscription',
            name='food_set',
            field=models.ManyToManyField(to='app_foods.food'),
        ),
    ]
