# Generated by Django 5.1.2 on 2024-10-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('is_premium', models.BooleanField(null=True)),
            ],
        ),
    ]
